// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkjvcyfzdqifiaiumkvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdranZjeWZ6ZHFpZmlhaXVta3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NjgyMTgsImV4cCI6MjA2MjE0NDIxOH0.HAbErz5U7CQlof0oa5xwxhHPG11E-X4U0AVmfQkhoyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);